#ifndef GRAPHICSCHARTSHAPESLIB_GLOBAL_H
#define GRAPHICSCHARTSHAPESLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPHICSCHARTSHAPESLIB_LIBRARY)
#  define GRAPHICSCHARTSHAPESLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GRAPHICSCHARTSHAPESLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHICSCHARTSHAPESLIB_GLOBAL_H
